version: '3.9'

services:
  payment_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 6800:5432
    networks:
      - payment_net
    deploy:  
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  payment:
    build: .
    environment:
      GUNICORN: false
    volumes:
      - .:/usr/app
    ports:
      - 6850:80
    networks:
      - payment_net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
    depends_on:
      payment_db:
        condition: service_started

networks:
  payment_net:
    driver: bridge
    name: payment_net