kind: Service
apiVersion: v1
metadata:
  name: service-payment
  annotations:
    cloud.google.com/backend-config: '{"default": "payment-config"}'
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31025